'use client'

import { useState } from 'react'
import { Watchlist } from '@/components/Watchlist'
import { NewsPanel } from '@/components/NewsPanel'
import { Chat } from '@/components/Chat'

export default function Home() {
  const [activeTicker, setActiveTicker] = useState<string | null>(null)

  const handleTickerSelect = (ticker: string) => {
    setActiveTicker(ticker)
  }

  return (
    <div className="min-h-screen bg-background p-4 md:p-8">
      <div className="mx-auto max-w-7xl">
        <header className="mb-8">
          <h1 className="text-3xl font-bold tracking-tight">Finance Copilot</h1>
          <p className="text-muted-foreground">
            Real-time market data and AI-powered financial insights
          </p>
        </header>

        <div className="grid gap-6 lg:grid-cols-2">
          {/* Left Column: Watchlist */}
          <div className="space-y-6">
            <Watchlist onTickerSelect={handleTickerSelect} />
          </div>

          {/* Right Column: News and Chat */}
          <div className="space-y-6">
            <NewsPanel ticker={activeTicker} />
            <Chat ticker={activeTicker} />
          </div>
        </div>

        {/* Risk Disclaimer Footer */}
        <footer className="mt-12 border-t pt-6">
          <div className="mx-auto max-w-7xl">
            <p className="text-xs text-muted-foreground">
              <strong>Disclaimer:</strong> This application provides financial information and AI-powered insights for educational purposes only. 
              It does not constitute financial advice, investment recommendations, or solicitation to buy or sell securities. 
              All market data is provided for informational purposes and may be delayed or inaccurate. 
              Past performance does not guarantee future results. Always consult with a qualified financial advisor before making investment decisions. 
              The AI assistant's responses are generated by machine learning models and should not be relied upon as the sole basis for financial decisions.
            </p>
          </div>
        </footer>
      </div>
    </div>
  )
}
